### ISSUE TITLE
TypeError: The compresed data passed is corrupted

### ISSUE THREAD

**Issue by mikeucfl** [sillyfrog/discord.js-listenexample#1]
Just curious if this code still works for you? When I ran it I saw this exception thrown from Decoder._decode when a recording was attempted

**Comment by sillyfrog** [comment]
I don't have that error - but it was not working with the latest `discord.js` as it required node 14, and other API changes.

This is now all updated, including another helper script (to convert the pcm files to wav).

Try pulling the latest update and doing a full build, hopefully it'll work for you.

Let me know how you go.

**Comment by mikeucfl** [comment]
Yeah everything is working now, seems passing "intents: Discord.Intents.ALL" fixes the issue. Thanks!

**Comment by mikeucfl** [comment]
So I ran into the issue again, however it seems to be related to using discord on chrome to talk and let the bot record vs using the discord app on desktop. Using chrome I get exceptions about the stream being corrupt, but the desktop app works fine. Figured I'd mention it just in case anyone else ran into this issue. Thanks again.

**Comment by sillyfrog** [comment]
That's interesting as the actual decoding is done by the core discord.js lib. Maybe worth logging an issue (or checking if it's known) with them. As if it's fixed there, it should also work here.
